### PR TITLE
fixed react warnings

### PR DESCRIPTION
**Pull request by janstuemmel**
* fixed React PropTypes warning
* fixed React creatClass warning

related with #60 #61

### CODE REVIEW

**Comment by janstuemmel** [comment]
I forked the repo, added some tests and published it on npm at react-mce

**Comment by ben-burlingham** [comment]
Thank you for this!  Any idea when it will make it into master?

**Comment by janstuemmel** [comment]
it won't. my fork implements some useful testcases, but a few more are welcome. just use `npm install --save react-mce`

**Comment by gugadev** [comment]
@mzabriskie dude, can you look at this? seems to work :)

**Pull request closed without merging**
