### PR TITLE
Allow Chaining of config.setup for Editor Init

### PR DESCRIPTION
**Pull request by apelican**
This modifies config use of the setup callback by chaining it after wrapper tasks. The wrapper still uses this setup routine to proxy events and set initial content. We needed the ability to configure custom buttons with callbacks easily defined within our component.

This allows configuration similar to the official [TinyMCE examples](http://www.tinymce.com/tryit/3_x/custom_toolbar_button.php).

### CODE REVIEW

**Comment by tenfef** [comment]
Would love to have this merged. As currently I can't see a way to add custom buttons to the toolbar as per this doc:
https://www.tinymce.com/docs/demo/custom-toolbar-button/

**Comment by lucidlive** [comment]
Thanks so much for this - solved my issue of not being able to add custom buttons.

**Comment by vklein** [comment]
+1

**Comment by TroyAlford** [comment]
:+1: - this would be a great addition.

**Comment by dschoon** [comment]
Any update on merging this? I could really use it too.

**Comment by TroyAlford** [comment]
@mzabriskie - any possibility we could get some attention on this?

**Pull request merged**
